### ISSUE TITLE
Add tile for Covid protocol platform

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#4]
please add a tile for the following platform: https://www.covidcp.org/
This should go on this subpage:
https://covid.cd2h.org/forms_and_standards

here is some text:
CovidCP aims to publicize protocols from PIs that are open to collaboration: joining forces with other research teams to create a core protocol; admitting new sites under the existing PI and IRB; sharing anonymized interim and/or final data through vivli.org with other sites that choose to independently operate a trial under a similar protocol.

**Comment by monicacecilia** [comment]
Pinging @alexisgraves. :bowtie:

**Comment by alexisgraves** [comment]
Just to be sure I'm crediting everyone correctly, this is an effort led by Harvard in partnership with JHU? Each entry has a logo associated with it so I just want to make sure I use the correct image since COVIDCP doesn't seem to have a logo yet. I can also use a different image (or no image) if that would work better.

**Comment by mellybelly** [comment]
I would just list the JHU logo, there are many collaborating instistutions.

**Comment by alexisgraves** [comment]
@mellybelly @monicacecilia Thank you! The tile is up [here](https://covid.cd2h.org/forms_and_standards) with the JHU logo! Please let me know if you want any edits made :) .

**Comment by monicacecilia** [comment]
Thanks @alexisgraves - this work has now been completed. :bowtie:
