### ISSUE TITLE
Link UPenn short survey to covid site

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#8]
The UPenn survey should be the short form. (Columbia did the long version.)  It makes more sense to only link to the GitHub repo, because they don't want people to take the survey  outside of Penn; they want them to implement it at their site. 
For reference only: link to most current version:  https://redcap.med.upenn.edu/surveys/?s=CE83CNHFRT.

**Comment by alexisgraves** [comment]
Both the short and long form links have been dropped so it now only links to the GitHub repo.

**Comment by monicacecilia** [comment]
Dear @amvolz, if this has been completed to your satisfaction, please close. Thank you! :bowtie:

**Comment by amvolz** [comment]
@alexisgraves I know you said you did this, but I cannot find it on the site. When the 'For Researchers' tab is created, I believe it will go under there, and then direct to a page. It is not easy to find right now. Keep this open until the landing page is redesigned and placement is confirmed.

**Comment by alexisgraves** [comment]
Hi @amvolz no worries, we can definitely make that whole list of CRFs more prominent with the new redesign! That specific UPenn item is on the [CRF page](https://covid.cd2h.org/forms_and_standards) right now, so I think it will just be a matter of linking that whole page in a more visible place so that it won't be as hard to find. One thing we might want to consider is that **CLIC is linking to our CRF list on their main [COVID page](https://clic-ctsa.org/covid-19)**, so we might not want to change the URL or setup too much or else the information on CLIC might become obsolete. You guys would definitely know better about that though!!!

**Comment by amvolz** [comment]
@alexisgraves I was getting ready to close this, as it does exist under the Resources-CRF menu. However, when I clicked on the link, I don't see a link to the actual REDCap survey, only links to the code book and data dictionary. I believe Melissa wants to have their actual survey available?

**Comment by amvolz** [comment]
@mellybelly Per some prior emails, it looks like Marilyn thought it was better to only link the GitHub repo and not the actual UPenn REDCap survey. See my first comment in this ticket; those are Marilyn's words (not mine) lifted from her email. So that's what we have under RESOURCES-FORMS, STANDARDS, PROTOCOLS -- UPenn.  Is that sufficient and can we close this ticket now?

**Comment by amvolz** [comment]
I believe we have satisfied this request. The UPenn survey is on the N3C website under the RESOURCES tab and linked to UPenn's GitHub  site that houses their REDCap survey and its data dictionary.
